TYPE=VIEW
query=select `csit77_suraj`.`instructor`.`instructor_id` AS `id`,`csit77_suraj`.`instructor`.`instructor_name` AS `name`,`csit77_suraj`.`instructor`.`dept_name` AS `dept_name` from `csit77_suraj`.`instructor`
md5=c8ba7612639010de2e913094debca088
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001689247911471136
create-version=2
source=SELECT instructor_id AS id, instructor_name AS name, dept_name FROM instructor
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `csit77_suraj`.`instructor`.`instructor_id` AS `id`,`csit77_suraj`.`instructor`.`instructor_name` AS `name`,`csit77_suraj`.`instructor`.`dept_name` AS `dept_name` from `csit77_suraj`.`instructor`
mariadb-version=100428
